# config.yaml
# Data Path
data_root: &data_root home/kuinisw5/data
econfinnews_raw: !join [*data_root, EconFinNews_Raw.json]

# Hypergraph Option
graph_type: &g_t hypergraph
K_neigs: [10, 15, 20] # [10]
m_prob: 0.8 # 1.0
is_probH: True

# Model
on_dataset: &o_d EconFinNews

# Result Path
result_root: &r_r home/kuinisw5/result/hgnn
result_sub_folder: !join [*r_r, !concat [ *g_t, _, *o_d ]]
ckpt_folder: !join [*r_r, ckpt]

# Train
max_epoch: 800
n_hid: 256
lr: 0.0005
milestones: [100]
gamma: 0.9
drop_out: 0.3
print_freq: 50
weight_decay: 0.0005
decay_step: 150
decay_rate: 0.8